apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 25565
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      nodePort: 25575
      protocol: TCP
    - name: bluemap
      port: 8100
      targetPort: 8100
      nodePort: 30100
      protocol: TCP
