apiVersion: v1
kind: ConfigMap
metadata:
  name: mineforge-web-nginx
  namespace: minecraft
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://mineforge-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
