apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mineforge-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zachary-perlmutter/mineforge-ai.git
    targetRevision: HEAD
    path: k8s/agent
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
